#!/bin/bash

log_dir="/log"
_puid=$(printenv PUID)
_pgid=$(printenv PGID)
mount_dir="/mount"
rclone_config="--config=/config/rclone.conf"
rclone_options="${rclone_config} --attr-timeout 1s --allow-non-empty --allow-other --uid ${_puid:-911} --gid ${_pgid:-911}"

if [ "$(printenv RCLONE_DISABLE_MEMORY_CACHE)" -eq "1" ]; then
    rclone_options="${rclone_config} --cache-chunk-no-memory"
fi
